### PR TITLE
Extra TestCase to prepend to Doctrine

### PR DESCRIPTION
**Pull request by Hanmac**
Final Testcase to test the prepend Doctrine Config line

### CODE REVIEW

**Comment by Hanmac** [comment]
direct usage of DoctrineExtension doesn't work, because of some dependency problem between doctrine-bundle and doctrine-bridge

but the test case was just for checking if the config gets prepended anyway

**Comment by Hanmac** [comment]
@loevgaard do you think this is ready to make the coverage to 100% ?

**Comment by Hanmac** [comment]
@loevgaard is this good or do we need more checks?

**Comment by Hanmac** [comment]
@Setono , someone has time to look into this?

**Comment by Hanmac** [comment]
@loevgaard i fixed the other issues with coding style too

**Comment by loevgaard** [comment]
You have done a great job, @Hanmac. Thank you :)

**Pull request merged**
