### PR TITLE
Remove support of Symfony 4

### PR DESCRIPTION
**Pull request by or-benjamin**
Symfony 4 is pretty old and #43 is not compatible with it

### CODE REVIEW

**Comment by loevgaard** [comment]
You need to update the build also :)

**Comment by or-benjamin** [comment]
I'ts done. Sorry it's the first time I make pull request for a project.

**Comment by loevgaard** [comment]
Great, @or-benjamin! Let's get this working together then :)

**Comment by loevgaard** [comment]
Now you can rebase your other PR onto `master`

**Pull request merged**
